Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\_submit.py", line 11, in <module>
    submitit_main()
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\submission.py", line 76, in submitit_main
    process_job(args.folder)
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\submission.py", line 52, in process_job
    delayed = utils.DelayedSubmission.load(paths.submitted_pickle)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\utils.py", line 153, in load
    obj = pickle_load(filepath)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\utils.py", line 232, in pickle_load
    return pickle.load(ifile)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\Desktop\VS_CODE\HOME\ML\work\VLG-CBM\train_cbm.py", line 9, in <module>
    import torch
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torch\__init__.py", line 1954, in <module>
    _C._initExtension(_manager_path())
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torch\cuda\__init__.py", line 264, in <module>
    _lazy_call(_check_capability)
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torch\cuda\__init__.py", line 261, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\traceback.py", line 218, in format_stack
    return format_list(extract_stack(f, limit=limit))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\traceback.py", line 232, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\traceback.py", line 395, in extract
    return klass._extract_from_extended_frame_gen(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\traceback.py", line 438, in _extract_from_extended_frame_gen
    f.line
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\traceback.py", line 323, in line
    self._line = linecache.getline(self.filename, self.lineno)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\linecache.py", line 93, in updatecache
    stat = os.stat(fullname)
           ^^^^^^^^^^^^^^^^^
KeyboardInterrupt
submitit ERROR (2025-01-02 19:52:52,385) - Submitted job triggered an exception
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\_submit.py", line 11, in <module>
    submitit_main()
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\submission.py", line 76, in submitit_main
    process_job(args.folder)
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\submission.py", line 69, in process_job
    raise error
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\submission.py", line 54, in process_job
    env._handle_signals(paths, delayed)
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\job_environment.py", line 153, in _handle_signals
    signal.signal(self._usr_sig(), handler.checkpoint_and_try_requeue)
                  ^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\job_environment.py", line 141, in _usr_sig
    raise RuntimeError(
RuntimeError: Unknown signal SIGUSR2, you may need to unset or update env var SUBMITIT_PREEMPT_SIGNAL (Eg: USR2)
