submitit ERROR (2025-01-02 19:50:38,116) - Submitted job triggered an exception
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\_submit.py", line 11, in <module>
    submitit_main()
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\submission.py", line 76, in submitit_main
    process_job(args.folder)
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\submission.py", line 69, in process_job
    raise error
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\submission.py", line 52, in process_job
    delayed = utils.DelayedSubmission.load(paths.submitted_pickle)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\utils.py", line 153, in load
    obj = pickle_load(filepath)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\submitit\core\utils.py", line 232, in pickle_load
    return pickle.load(ifile)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\Desktop\VS_CODE\HOME\ML\work\VLG-CBM\train_cbm.py", line 16, in <module>
    import model.utils as utils
  File "C:\Users\debryu\Desktop\VS_CODE\HOME\ML\work\VLG-CBM\model\utils.py", line 5, in <module>
    import clip
  File "C:\Users\debryu\Desktop\VS_CODE\HOME\ML\work\VLG-CBM\clip\__init__.py", line 1, in <module>
    from .clip import *
  File "C:\Users\debryu\Desktop\VS_CODE\HOME\ML\work\VLG-CBM\clip\clip.py", line 10, in <module>
    from torchvision.transforms import Compose, Resize, CenterCrop, ToTensor, Normalize
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torchvision\__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torchvision\models\__init__.py", line 2, in <module>
    from .convnext import *
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torchvision\models\convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torchvision\ops\__init__.py", line 23, in <module>
    from .poolers import MultiScaleRoIAlign
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torchvision\ops\poolers.py", line 10, in <module>
    from .roi_align import roi_align
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torchvision\ops\roi_align.py", line 7, in <module>
    from torch._dynamo.utils import is_compile_supported
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torch\_dynamo\__init__.py", line 3, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torch\_dynamo\convert_frame.py", line 53, in <module>
    from . import config, exc, trace_rules
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torch\_dynamo\trace_rules.py", line 3500, in <module>
    add(_name)
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torch\_dynamo\trace_rules.py", line 3366, in add
    _recompile_re()
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torch\_dynamo\trace_rules.py", line 3349, in _recompile_re
    rf"^[^\s<]*({'|'.join(re.escape(_as_posix_path(d)) for d in SKIP_DIRS)})"
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torch\_dynamo\trace_rules.py", line 3349, in <genexpr>
    rf"^[^\s<]*({'|'.join(re.escape(_as_posix_path(d)) for d in SKIP_DIRS)})"
                                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\site-packages\torch\_dynamo\trace_rules.py", line 3162, in _as_posix_path
    posix_path = Path(os.path.normpath(path)).as_posix()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\pathlib.py", line 454, in as_posix
    return str(self).replace(f.sep, '/')
           ^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\pathlib.py", line 443, in __str__
    self._str = self._format_parsed_parts(self.drive, self.root,
                                          ^^^^^^^^^^
  File "C:\Users\debryu\anaconda3\envs\vlg-cbm\Lib\pathlib.py", line 557, in drive
    self._load_parts()
MemoryError
